CREATE TABLE NOTIFICATION
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOTIFIER BIGINT NOT NULL,
    RECEIVER BIGINT NOT NULL,
    OUTERID BIGINT NOT NULL,
    TYPE INT NOT NULL,
    GMT_CREATE BIGINT NOT NULL,
    STATUS INT DEFAULT 0 NOT NULL
);