CREATE TABLE NAV
(
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TITLE VARCHAR(100),
    URL VARCHAR(256),
    PRIORITY INT DEFAULT 0,
    GMT_CREATE BIGINT,
    GMT_MODIFIED BIGINT,
    STATUS INT
);