CREATE TABLE AD
(
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TITLE VARCHAR(256) DEFAULT NULL,
    URL VARCHAR(512) DEFAULT NULL,
    IMAGE VARCHAR(256) DEFAULT NULL,
    GMT_START BIGINT,
    GMT_END BIGINT,
    GMT_CREATE BIGINT,
    GMT_MODIFIED BIGINT,
    STATUS INT,
    POS VARCHAR(10) NOT NULL
);